# Generated by Django 2.2 on 2020-05-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SandRCustom_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
