# Generated by Django 2.2 on 2020-05-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SandRCustom_app', '0002_auto_20200517_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color1',
            field=models.CharField(default='color', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='color2',
            field=models.CharField(default='color', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.CharField(default='text', max_length=255),
        ),
    ]
